
import { z } from 'zod';

// --- Input/Output Schemas for Image Generation ---
export const GenerateImageInputSchema = z.object({
  promptText: z.string().describe('The text prompt to use for image generation.'),
  userId: z.string().describe('The ID of the user generating the image.'),
});
export type GenerateImageInput = z.infer<typeof GenerateImageInputSchema>;

export const GenerateImageOutputSchema = z.object({
  imageDataUri: z.string().describe('The generated image as a data URI.'),
  generatedDescription: z.string().optional().describe('The detailed description of the image generated by the AI.'),
});
export type GenerateImageOutput = z.infer<typeof GenerateImageOutputSchema>;

// --- Media Management Schemas & Types ---
export const UserMediaSchema = z.object({
    id: z.string(),
    userId: z.string(),
    type: z.enum(['ai-generated', 'community-chat', 'ticket-media']),
    mediaUrl: z.string(),
    prompt: z.string().optional(),
    createdAt: z.string().datetime({ offset: true }),
    expiresAt: z.string().datetime({ offset: true }),
});
export type UserMedia = z.infer<typeof UserMediaSchema>;

export const SaveMediaInputSchema = UserMediaSchema.pick({
    userId: true,
    type: true,
    mediaUrl: true,
    prompt: true,
});
export type SaveMediaInput = z.infer<typeof SaveMediaInputSchema>;
