
export const cryptoCurrencies = [
  { code: "BTC", name: "Bitcoin" },
  { code: "ETH", name: "Ethereum" },
  { code: "USDT", name: "Tether" },
  { code: "BNB", name: "BNB" },
  { code: "SOL", name: "Solana" },
  { code: "XRP", name: "XRP" },
  { code: "USDC", name: "USDC" },
  { code: "ADA", name: "Cardano" },
  { code: "DOGE", name: "Dogecoin" },
  { code: "AVAX", name: "Avalanche" },
  { code: "SHIB", name: "Shiba Inu" },
  { code: "DOT", name: "Polkadot" },
  { code: "TRX", name: "TRON" },
  { code: "LINK", name: "Chainlink" },
  { code: "MATIC", name: "Polygon" },
  { code: "BCH", name: "Bitcoin Cash" },
  { code: "ICP", name: "Internet Computer" },
  { code: "LTC", name: "Litecoin" },
  { code: "NEAR", name: "NEAR Protocol" },
  { code: "LEO", name: "UNUS SED LEO" },
  { code: "UNI", name: "Uniswap" },
  { code: "DAI", name: "Dai" },
  { code: "ETC", name: "Ethereum Classic" },
  { code: "ATOM", name: "Cosmos" },
  { code: "OP", name: "Optimism" },
  { code: "IMX", name: "Immutable X" },
  { code: "XLM", name: "Stellar" },
  { code: "OKB", name: "OKB" },
  { code: "RNDR", name: "Render Token" },
  { code: "HBAR", name: "Hedera" },
  { code: "FIL", name: "Filecoin" },
  { code: "CRO", name: "Cronos" },
  { code: "INJ", name: "Injective" },
  { code: "VET", name: "VeChain" },
  { code: "MKR", name: "Maker" },
  { code: "TAO", name: "Bittensor" },
  { code: "GRT", name: "The Graph" },
  { code: "LDO", name: "Lido DAO" },
  { code: "AR", name: "Arweave" },
  { code: "THETA", name: "Theta Network" },
  { code: "TUSD", name: "TrueUSD" },
  { code: "BGB", name: "Bitget Token" },
  { code: "AAVE", name: "Aave" },
  { code: "ALGO", name: "Algorand" },
  { code: "SEI", name: "Sei" },
  { code: "FLOW", name: "Flow" },
  { code: "QNT", name: "Quant" },
  { code: "STX", name: "Stacks" },
  { code: "EGLD", name: "MultiversX" },
  { code: "SUI", name: "Sui" },
  { code: "GALA", name: "Gala" },
  { code: "BEAM", name: "Beam" },
  { code: "SAND", name: "The Sandbox" },
  { code: "AXS", name: "Axie Infinity" },
  { code: "FTM", name"Fantom" },
  { code: "EOS", name: "EOS" },
  { code: "XTZ", name: "Tezos" },
  { code: "MANA", name: "Decentraland" },
  { code: "KCS", name: "KuCoin Token" },
  { code: "NEO", name: "Neo" },
  { code: "IOTA", name: "IOTA" },
  { code: "CHZ", name: "Chiliz" },
  { code: "KAVA", name: "Kava" },
  { code: "ZEC", name: "Zcash" },
  { code: "XEC", name: "eCash" },
  { code: "KLAY", name: "Klaytn" },
  { code: "GNO", name: "Gnosis" },
  { code: "RUNE", name: "THORChain" },
  { code: "TWT", name: "Trust Wallet Token" },
  { code: "MINA", name: "Mina" },
  { code: "CAKE", name: "PancakeSwap" },
  { code: "GMX", name: "GMX" },
  { code: "XDC", name: "XDC Network" },
  { code: "XMR", name: "Monero" },
  { code: "ZIL", name: "Zilliqa" },
  { code: "WEMIX", name: "WEMIX" },
  { code: "LUNC", name: "Terra Classic" },
  { code: "BTG", name: "Bitcoin Gold" },
  { code: "DASH", name: "Dash" },
  { code: "CRV", name: "Curve DAO Token" },
  { code: "NEXO", name: "Nexo" },
  { code: "PAXG", name: "PAX Gold" },
  { code: "ENJ", name: "Enjin Coin" },
  { code: "1INCH", name: "1inch Network" },
  { code: "DYDX", name: "dYdX" },
  { code: "CELO", name: "Celo" },
  { code: "QTUM", name: "Qtum" },
  { code: "ANKR", name: "Ankr" },
  { code: "HNT", name: "Helium" },
  { code: "WAVES", name: "Waves" },
  { code: "KSM", name: "Kusama" },
  { code: "RVN", name: "Ravencoin" },
  { code: "COMP", name: "Compound" },
  { code: "AR", name: "Arweave" },
];
