
'use client';

import dynamic from 'next/dynamic';
import React, { FC } from 'react';
import { Loader2 } from 'lucide-react';

/**
 * Optimized Tool Loading Component
 */
const LoadingComponent = () => (
  <div className="flex flex-col justify-center items-center min-h-[300px] space-y-4">
    <Loader2 className="h-10 w-10 animate-spin text-primary" />
    <p className="text-muted-foreground animate-pulse font-medium">Opening Tool...</p>
  </div>
);

/**
 * Centralized High-Performance Tool Map
 * Every tool is imported lazily to ensure lightning fast initial page loads.
 */
export const slugToComponentMap: Record<string, FC<any>> = {
  'advance-text-cleaner': dynamic(() => import('@/components/tools/AdvanceTextCleaner'), { loading: LoadingComponent, ssr: false }),
  'admob-revenue-calculator': dynamic(() => import('@/components/tools/AdMobRevenueCalculator').then(mod => mod.AdMobRevenueCalculator), { loading: LoadingComponent, ssr: false }),
  'age-calculator': dynamic(() => import('@/components/tools/AgeCalculator'), { loading: LoadingComponent, ssr: false }),
  'amazon-shipping-label-cropper': dynamic(() => import('@/components/tools/AmazonShippingLabelCropper'), { loading: LoadingComponent, ssr: false }),
  'ascii-to-text-converter': dynamic(() => import('@/components/tools/AsciiToTextConverter'), { loading: LoadingComponent, ssr: false }),
  'average-calculator': dynamic(() => import('@/components/tools/AverageCalculator'), { loading: LoadingComponent, ssr: false }),
  'barcode-generator': dynamic(() => import('@/components/tools/BarcodeGenerator'), { loading: LoadingComponent, ssr: false }),
  'barcode-scanner': dynamic(() => import('@/components/tools/BarcodeScanner'), { loading: LoadingComponent, ssr: false }),
  'base64-encoder-and-decoder': dynamic(() => import('@/components/tools/Base64Converter'), { loading: LoadingComponent, ssr: false }),
  'binary-to-text': dynamic(() => import('@/components/tools/BinaryToText'), { loading: LoadingComponent, ssr: false }),
  'bmi-calculator': dynamic(() => import('@/components/tools/BmiCalculator'), { loading: LoadingComponent, ssr: false }),
  'case-converter': dynamic(() => import('@/components/tools/CaseConverter'), { loading: LoadingComponent, ssr: false }),
  'cgpa-to-gpa-converter': dynamic(() => import('@/components/tools/CgpaToGpaConverter'), { loading: LoadingComponent, ssr: false }),
  'cgpa-to-marks-calculator': dynamic(() => import('@/components/tools/CgpaToMarksCalculator'), { loading: LoadingComponent, ssr: false }),
  'color-picker': dynamic(() => import('@/components/tools/ColorPicker'), { loading: LoadingComponent, ssr: false }),
  'compress-pdf': dynamic(() => import('@/components/tools/CompressPdf'), { loading: LoadingComponent, ssr: false }),
  'credit-card-interest-calculator': dynamic(() => import('@/components/tools/CreditCardInterestCalculator'), { loading: LoadingComponent, ssr: false }),
  'crontab-generator': dynamic(() => import('@/components/tools/CrontabGenerator'), { loading: LoadingComponent, ssr: false }),
  'crypto-converter': dynamic(() => import('@/components/tools/CryptoConverter'), { loading: LoadingComponent, ssr: false }),
  'css-minifier': dynamic(() => import('@/components/tools/CssMinifier'), { loading: LoadingComponent, ssr: false }),
  'currency-converter': dynamic(() => import('@/components/tools/CurrencyConverter'), { loading: LoadingComponent, ssr: false }),
  'date-calculator': dynamic(() => import('@/components/tools/DateCalculator'), { loading: LoadingComponent, ssr: false }),
  'discount-calculator': dynamic(() => import('@/components/tools/DiscountCalculator'), { loading: LoadingComponent, ssr: false }),
  'driving-licence-photo-and-signature-resizer': dynamic(() => import('@/components/tools/DrivingLicenceResizer'), { loading: LoadingComponent, ssr: false }),
  'dropbox-direct-link-generator': dynamic(() => import('@/components/tools/DropboxDirectLinkGenerator'), { loading: LoadingComponent, ssr: false }),
  'excel-to-pdf': dynamic(() => import('@/components/tools/ExcelToPdf'), { loading: LoadingComponent, ssr: false }),
  'favicon-checker': dynamic(() => import('@/components/tools/FaviconChecker'), { loading: LoadingComponent, ssr: false }),
  'find-and-replace': dynamic(() => import('@/components/tools/FindAndReplace'), { loading: LoadingComponent, ssr: false }),
  'flipkart-shipping-label-cropper': dynamic(() => import('@/components/tools/FlipkartShippingLabelCropper'), { loading: LoadingComponent, ssr: false }),
  'flip-image': dynamic(() => import('@/components/tools/FlipImage'), { loading: LoadingComponent, ssr: false }),
  'fuel-cost-calculator': dynamic(() => import('@/components/tools/FuelCostCalculator'), { loading: LoadingComponent, ssr: false }),
  'gpa-calculator': dynamic(() => import('@/components/tools/GpaCalculator'), { loading: LoadingComponent, ssr: false }),
  'gpa-to-cgpa-calculator': dynamic(() => import('@/components/tools/GpaToCgpaCalculator'), { loading: LoadingComponent, ssr: false }),
  'gpa-to-percentage-converter': dynamic(() => import('@/components/tools/GpaToPercentageConverter'), { loading: LoadingComponent, ssr: false }),
  'gst-calculator': dynamic(() => import('@/components/tools/GSTCalculator'), { loading: LoadingComponent, ssr: false }),
  'google-drive-direct-link-generator': dynamic(() => import('@/components/tools/GoogleDriveDirectLinkGenerator'), { loading: LoadingComponent, ssr: false }),
  'html-minifier': dynamic(() => import('@/components/tools/HtmlMinifier'), { loading: LoadingComponent, ssr: false }),
  'html-to-markdown-converter': dynamic(() => import('@/components/tools/HtmlToMarkdownConverter'), { loading: LoadingComponent, ssr: false }),
  'ico-converter': dynamic(() => import('@/components/tools/IcoConverter'), { loading: LoadingComponent, ssr: false }),
  'image-color-extractor': dynamic(() => import('@/components/tools/ImageColorExtractor'), { loading: LoadingComponent, ssr: false }),
  'image-compressor': dynamic(() => import('@/components/tools/ImageCompressor'), { loading: LoadingComponent, ssr: false }),
  'image-converter': dynamic(() => import('@/components/tools/ImageConverter'), { loading: LoadingComponent, ssr: false }),
  'image-cropper': dynamic(() => import('@/components/tools/ImageCropper'), { loading: LoadingComponent, ssr: false }),
  'image-grayscale-converter': dynamic(() => import('@/components/tools/ImageGrayscaleConverter'), { loading: LoadingComponent, ssr: false }),
  'image-resizer': dynamic(() => import('@/components/tools/ImageResizer'), { loading: LoadingComponent, ssr: false }),
  'image-shape-converter': dynamic(() => import('@/components/tools/ImageShapeConverter'), { loading: LoadingComponent, ssr: false }),
  'image-to-base64': dynamic(() => import('@/components/tools/ImageToBase64'), { loading: LoadingComponent, ssr: false }),
  'image-watermark-adder': dynamic(() => import('@/components/tools/ImageWatermarkAdder'), { loading: LoadingComponent, ssr: false }),
  'image-metadata-viewer': dynamic(() => import('@/components/tools/ImageMetadataViewer'), { loading: LoadingComponent, ssr: false }),
  'interest-calculator': dynamic(() => import('@/components/tools/InterestCalculator'), { loading: LoadingComponent, ssr: false }),
  'javascript-minifier': dynamic(() => import('@/components/tools/JavascriptMinifier'), { loading: LoadingComponent, ssr: false }),
  'json-formatter': dynamic(() => import('@/components/tools/JsonFormatter'), { loading: LoadingComponent, ssr: false }),
  'keyword-density-checker': dynamic(() => import('@/components/tools/KeywordDensityChecker'), { loading: LoadingComponent, ssr: false }),
  'loan-calculator': dynamic(() => import('@/components/tools/LoanCalculator'), { loading: LoadingComponent, ssr: false }),
  'lock-pdf': dynamic(() => import('@/components/tools/LockPdf'), { loading: LoadingComponent, ssr: false }),
  'lorem-ipsum-generator': dynamic(() => import('@/components/tools/LoremIpsumGenerator'), { loading: LoadingComponent, ssr: false }),
  'marks-to-percentage-calculator': dynamic(() => import('@/components/tools/MarksToPercentageCalculator'), { loading: LoadingComponent, ssr: false }),
  'meesho-shipping-label-cropper': dynamic(() => import('@/components/tools/MeeshoShippingLabelCropper'), { loading: LoadingComponent, ssr: false }),
  'meta-tag-generator': dynamic(() => import('@/components/tools/MetaTagGenerator'), { loading: LoadingComponent, ssr: false }),
  'morse-to-text-translator': dynamic(() => import('@/components/tools/MorseToTextTranslator'), { loading: LoadingComponent, ssr: false }),
  'myntra-shipping-label-cropper': dynamic(() => import('@/components/tools/MyntraShippingLabelCropper'), { loading: LoadingComponent, ssr: false }),
  'negative-marking-calculator': dynamic(() => import('@/components/tools/NegativeMarkingCalculator'), { loading: LoadingComponent, ssr: false }),
  'nsdl-pan-card-photo-and-signature-resizer': dynamic(() => import('@/components/tools/NSDLPANCardPhotoAndSignatureResizer'), { loading: LoadingComponent, ssr: false }),
  'onedrive-direct-link-generator': dynamic(() => import('@/components/tools/OneDriveDirectLinkGenerator'), { loading: LoadingComponent, ssr: false }),
  'password-generator': dynamic(() => import('@/components/tools/PasswordGenerator'), { loading: LoadingComponent, ssr: false }),
  'password-strength-checker': dynamic(() => import('@/components/tools/PasswordStrengthChecker'), { loading: LoadingComponent, ssr: false }),
  'pdf-merger': dynamic(() => import('@/components/tools/PdfMerger'), { loading: LoadingComponent, ssr: false }),
  'pdf-organizer': dynamic(() => import('@/components/tools/PdfOrganizer'), { loading: LoadingComponent, ssr: false }),
  'pdf-page-counter': dynamic(() => import('@/components/tools/PdfPageCounter'), { loading: LoadingComponent, ssr: false }),
  'pdf-page-numberer': dynamic(() => import('@/components/tools/PdfPageNumberer'), { loading: LoadingComponent, ssr: false }),
  'pdf-page-remover': dynamic(() => import('@/components/tools/PdfPageRemover'), { loading: LoadingComponent, ssr: false }),
  'pdf-page-reorder': dynamic(() => import('@/components/tools/PdfPageReorder'), { loading: LoadingComponent, ssr: false }),
  'pdf-signer': dynamic(() => import('@/components/tools/PdfSigner'), { loading: LoadingComponent, ssr: false }),
  'pdf-splitter': dynamic(() => import('@/components/tools/PdfSplitter'), { loading: LoadingComponent, ssr: false }),
  'pdf-to-jpg': dynamic(() => import('@/components/tools/PdfToJpg'), { loading: LoadingComponent, ssr: false }),
  'pdf-to-word': dynamic(() => import('@/components/tools/PdfToWord'), { loading: LoadingComponent, ssr: false }),
  'percentage-calculator': dynamic(() => import('@/components/tools/PercentageCalculator'), { loading: LoadingComponent, ssr: false }),
  'percentage-to-cgpa-converter': dynamic(() => import('@/components/tools/PercentageToCgpaConverter'), { loading: LoadingComponent, ssr: false }),
  'ppt-to-pdf': dynamic(() => import('@/components/tools/PptToPdf'), { loading: LoadingComponent, ssr: false }),
  'qr-code-generator': dynamic(() => import('@/components/tools/QrCodeGenerator'), { loading: LoadingComponent, ssr: false }),
  'qr-code-scanner': dynamic(() => import('@/components/tools/QrCodeScanner'), { loading: LoadingComponent, ssr: false }),
  'random-word-generator': dynamic(() => import('@/components/tools/RandomWordGenerator'), { loading: LoadingComponent, ssr: false }),
  'readability-score-checker': dynamic(() => import('@/components/tools/ReadabilityScoreChecker'), { loading: LoadingComponent, ssr: false }),
  'remove-extra-spaces': dynamic(() => import('@/components/tools/RemoveExtraSpaces'), { loading: LoadingComponent, ssr: false }),
  'redirect-checker': dynamic(() => import('@/components/tools/RedirectChecker'), { loading: LoadingComponent, ssr: false }),
  'reverse-text': dynamic(() => import('@/components/tools/ReverseText'), { loading: LoadingComponent, ssr: false }),
  'robots-txt-generator': dynamic(() => import('@/components/tools/RobotsTxtGenerator'), { loading: LoadingComponent, ssr: false }),
  'rotate-image': dynamic(() => import('@/components/tools/RotateImage'), { loading: LoadingComponent, ssr: false }),
  'rotate-pdf': dynamic(() => import('@/components/tools/RotatePdf'), { loading: LoadingComponent, ssr: false }),
  'schema-generator': dynamic(() => import('@/components/tools/SchemaGenerator'), { loading: LoadingComponent, ssr: false }),
  'serp-checker': dynamic(() => import('@/components/tools/SerpChecker'), { loading: LoadingComponent, ssr: false }),
  'sha256-hash-generator': dynamic(() => import('@/components/tools/Sha256HashGenerator'), { loading: LoadingComponent, ssr: false }),
  'sku-encryptor': dynamic(() => import('@/components/tools/SkuEncryptor'), { loading: LoadingComponent, ssr: false }),
  'srm-to-cgpa-calculator': dynamic(() => import('@/components/tools/SrmToCgpaCalculator'), { loading: LoadingComponent, ssr: false }),
  'sql-formatter': dynamic(() => import('@/components/tools/SqlFormatter'), { loading: LoadingComponent, ssr: false }),
  'text-repeater': dynamic(() => import('@/components/tools/TextRepeater'), { loading: LoadingComponent, ssr: false }),
  'text-to-binary': dynamic(() => import('@/components/tools/TextToBinary'), { loading: LoadingComponent, ssr: false }),
  'text-to-morse-code': dynamic(() => import('@/components/tools/TextToMorseCode'), { loading: LoadingComponent, ssr: false }),
  'file-encryption-and-decryption': dynamic(() => import('@/components/tools/FileEncryptionDecryption'), { loading: LoadingComponent, ssr: false }),
  'image-to-text': dynamic(() => import('@/components/tools/ImageToText'), { loading: LoadingComponent, ssr: false }),
  'time-zone-converter': dynamic(() => import('@/components/tools/TimeZoneConverter'), { loading: LoadingComponent, ssr: false }),
  'title-tag-checker': dynamic(() => import('@/components/tools/TitleTagChecker'), { loading: LoadingComponent, ssr: false }),
  'unix-timestamp-converter': dynamic(() => import('@/components/tools/UnixTimestampConverter'), { loading: LoadingComponent, ssr: false }),
  'universal-hash-generator': dynamic(() => import('@/components/tools/UniversalHashGenerator'), { loading: LoadingComponent, ssr: false }),
  'unlock-pdf': dynamic(() => import('@/components/tools/UnlockPdf'), { loading: LoadingComponent, ssr: false }),
  'url-shortener': dynamic(() => import('@/components/tools/UrlShortener'), { loading: LoadingComponent, ssr: false }),
  'uuid-generator': dynamic(() => import('@/components/tools/UuidGenerator'), { loading: LoadingComponent, ssr: false }),
  'uti-pan-card-photo-and-signature-resizer': dynamic(() => import('@/components/tools/UTIPANCardPhotoAndSignatureResizer'), { loading: LoadingComponent, ssr: false }),
  'website-screenshot': dynamic(() => import('@/components/tools/WebsiteScreenshot'), { loading: LoadingComponent, ssr: false }),
  'website-word-counter': dynamic(() => import('@/components/tools/WebsiteWordCounter'), { loading: LoadingComponent, ssr: false }),
  'what-is-my-browser': dynamic(() => import('@/components/tools/WhatIsMyBrowser'), { loading: LoadingComponent, ssr: false }),
  'word-counter': dynamic(() => import('@/components/tools/WordCounter'), { loading: LoadingComponent, ssr: false }),
  'word-to-pdf': dynamic(() => import('@/components/tools/WordToPdf'), { loading: LoadingComponent, ssr: false }),
  'xml-sitemap-generator': dynamic(() => import('@/components/tools/XmlSitemapGenerator'), { loading: LoadingComponent, ssr: false }),
  'youtube-banner-downloader': dynamic(() => import('@/components/tools/YouTubeChannelBannerDownloader'), { loading: LoadingComponent, ssr: false }),
  'youtube-logo-downloader': dynamic(() => import('@/components/tools/YouTubeChannelLogoDownloader'), { loading: LoadingComponent, ssr: false }),
  'youtube-region-restriction-checker': dynamic(() => import('@/components/tools/YouTubeRegionRestrictionChecker'), { loading: LoadingComponent, ssr: false }),
  'youtube-video-description-extractor': dynamic(() => import('@/components/tools/YouTubeVideoDescriptionExtractor'), { loading: LoadingComponent, ssr: false }),
  'youtube-video-thumbnail-downloader': dynamic(() => import('@/components/tools/YouTubeVideoThumbnailDownloader'), { loading: LoadingComponent, ssr: false }),
  'youtube-video-title-extractor': dynamic(() => import('@/components/tools/YouTubeVideoTitleExtractor'), { loading: LoadingComponent, ssr: false }),
  'profit-loss-calculator': dynamic(() => import('@/components/tools/ProfitLossCalculator'), { loading: LoadingComponent, ssr: false }),
  'sip-calculator': dynamic(() => import('@/components/tools/SIPCalculator'), { loading: LoadingComponent, ssr: false }),
  'fd-calculator': dynamic(() => import('@/components/tools/FDCalculator'), { loading: LoadingComponent, ssr: false }),
  'mutual-fund-calculator': dynamic(() => import('@/components/tools/MutualFundCalculator'), { loading: LoadingComponent, ssr: false }),
  'sales-tax-calculator': dynamic(() => import('@/components/tools/SalesTaxCalculator'), { loading: LoadingComponent, ssr: false }),
  'tds-calculator': dynamic(() => import('@/components/tools/TDSCalculator'), { loading: LoadingComponent, ssr: false }),
  'image-aspect-ratio-calculator': dynamic(() => import('@/components/tools/ImageAspectRatioCalculator'), { loading: LoadingComponent, ssr: false }),
  'spelling-checker': dynamic(() => import('@/components/tools/SpellingChecker'), { loading: LoadingComponent, ssr: false }),
  'whats-chat-url-generator': dynamic(() => import('@/components/tools/WhatsChatUrlGenerator'), { loading: LoadingComponent, ssr: false }),
  'whats-app-group-url-generator': dynamic(() => import('@/components/tools/WhatsAppGroupUrlGenerator'), { loading: LoadingComponent, ssr: false }),
  'internet-speed-tester': dynamic(() => import('@/components/tools/InternetSpeedTester'), { loading: LoadingComponent, ssr: false }),
  'device-information-detector': dynamic(() => import('@/components/tools/DeviceInformationDetector'), { loading: LoadingComponent, ssr: false }),
  'numbers-to-word': dynamic(() => import('@/components/tools/NumbersToWord'), { loading: LoadingComponent, ssr: false }),
  'emoji-remover': dynamic(() => import('@/components/tools/EmojiRemover'), { loading: LoadingComponent, ssr: false }),
  'roman-to-number-converter': dynamic(() => import('@/components/tools/RomanToNumberConverter'), { loading: LoadingComponent, ssr: false }),
  'number-to-roman-converter': dynamic(() => import('@/components/tools/NumberToRomanConverter'), { loading: LoadingComponent, ssr: false }),
  'rd-calculator': dynamic(() => import('@/components/tools/RdCalculator'), { loading: LoadingComponent, ssr: false }),
  'nps-calculator': dynamic(() => import('@/components/tools/NpsCalculator'), { loading: LoadingComponent, ssr: false }),
  'adsense-revenue-calculator': dynamic(() => import('@/components/tools/AdSenseRevenueCalculator'), { loading: LoadingComponent, ssr: false }),
  'unit-converter': dynamic(() => import('@/components/tools/UnitConverter'), { loading: LoadingComponent, ssr: false }),
  'image-to-pdf': dynamic(() => import('@/components/tools/ImageToPdf'), { loading: LoadingComponent, ssr: false }),
  'epf-calculator': dynamic(() => import('@/components/tools/EPFCalculator'), { loading: LoadingComponent, ssr: false }),
  'gratuity-calculator': dynamic(() => import('@/components/tools/GratuityCalculator'), { loading: LoadingComponent, ssr: false }),
  'inflation-calculator': dynamic(() => import('@/components/tools/InflationCalculator'), { loading: LoadingComponent, ssr: false }),
  'loan-affordability-calculator': dynamic(() => import('@/components/tools/LoanAffordabilityCalculator'), { loading: LoadingComponent, ssr: false }),
  'nsc-calculator': dynamic(() => import('@/components/tools/NscCalculator'), { loading: LoadingComponent, ssr: false }),
  'ppf-calculator': dynamic(() => import('@/components/tools/PpfCalculator'), { loading: LoadingComponent, ssr: false }),
  'swp-calculator': dynamic(() => import('@/components/tools/SwpCalculator'), { loading: LoadingComponent, ssr: false }),
  'retirement-savings-calculator': dynamic(() => import('@/components/tools/RetirementSavingsCalculator'), { loading: LoadingComponent, ssr: false }),
  'mortgage-calculator': dynamic(() => import('@/components/tools/MortgageCalculator'), { loading: LoadingComponent, ssr: false }),
  'hra-calculator': dynamic(() => import('@/components/tools/HraCalculator'), { loading: LoadingComponent, ssr: false }),
  'text-to-handwriting-converter': dynamic(() => import('@/components/tools/TextToHandwritingConverter'), { loading: LoadingComponent, ssr: false }),
  'text-to-ascii-converter': dynamic(() => import('@/components/tools/TextToAsciiConverter'), { loading: LoadingComponent, ssr: false }),
  'random-name-generator': dynamic(() => import('@/components/tools/RandomNameGenerator'), { loading: LoadingComponent, ssr: false }),
  'ifsc-code-to-bank-details': dynamic(() => import('@/components/tools/IfscCodeToBankDetails'), { loading: LoadingComponent, ssr: false }),
  'text-to-speech': dynamic(() => import('@/components/tools/TextToSpeech').then(mod => mod.TextToSpeechTool), { loading: LoadingComponent, ssr: false }),
};
