
export const unitData = {
  length: {
    name: 'Length',
    units: [
      { value: 'm', label: 'Meter (m)' },
      { value: 'km', label: 'Kilometer (km)' },
      { value: 'cm', label: 'Centimeter (cm)' },
      { value: 'mm', label: 'Millimeter (mm)' },
      { value: 'μm', label: 'Micrometer (µm)' },
      { value: 'nm', label: 'Nanometer (nm)' },
      { value: 'mi', label: 'Mile (mi)' },
      { value: 'ft', label: 'Foot (ft)' },
      { value: 'in', label: 'Inch (in)' },
      { value: 'yd', label: 'Yard (yd)' },
      { value: 'nmi', label: 'Nautical Mile (nmi)' },
    ],
    factors: { m: 1, km: 1000, cm: 0.01, mm: 0.001, 'μm': 1e-6, nm: 1e-9, mi: 1609.34, ft: 0.3048, in: 0.0254, yd: 0.9144, nmi: 1852 },
  },
  mass: {
    name: 'Mass',
    units: [
      { value: 'kg', label: 'Kilogram (kg)' },
      { value: 'g', label: 'Gram (g)' },
      { value: 'mg', label: 'Milligram (mg)' },
      { value: 'μg', label: 'Microgram (µg)' },
      { value: 't', label: 'Tonne (t)' },
      { value: 'lb', label: 'Pound (lb)' },
      { value: 'oz', label: 'Ounce (oz)' },
      { value: 'st', label: 'Stone (st)' },
      { value: 'ton-us', label: 'US Ton' },
    ],
    factors: { kg: 1, g: 0.001, mg: 1e-6, 'μg': 1e-9, t: 1000, lb: 0.453592, oz: 0.0283495, st: 6.35029, 'ton-us': 907.185 },
  },
  temperature: {
    name: 'Temperature',
    units: [
      { value: 'Celsius', label: 'Celsius (°C)' },
      { value: 'Fahrenheit', label: 'Fahrenheit (°F)' },
      { value: 'Kelvin', label: 'Kelvin (K)' },
    ],
    factors: {}, // Special handling
  },
  area: {
    name: 'Area',
    units: [
      { value: 'sqm', label: 'Square Meter (m²)' },
      { value: 'sqkm', label: 'Square Kilometer (km²)' },
      { value: 'sqcm', label: 'Square Centimeter (cm²)' },
      { value: 'sqmi', label: 'Square Mile (mi²)' },
      { value: 'sqft', label: 'Square Foot (ft²)' },
      { value: 'sqyd', label: 'Square Yard (yd²)' },
      { value: 'acre', label: 'Acre' },
      { value: 'ha', label: 'Hectare (ha)' },
    ],
    factors: { sqm: 1, sqkm: 1e6, sqcm: 1e-4, sqmi: 2.59e6, sqft: 0.092903, sqyd: 0.836127, acre: 4046.86, ha: 10000 },
  },
  volume: {
    name: 'Volume',
    units: [
      { value: 'l', label: 'Liter (l)' },
      { value: 'ml', label: 'Milliliter (ml)' },
      { value: 'cubic-m', label: 'Cubic Meter (m³)' },
      { value: 'cubic-cm', label: 'Cubic Centimeter (cm³)' },
      { value: 'gal', label: 'Gallon (US)' },
      { value: 'qt', label: 'Quart (US)' },
      { value: 'pt', label: 'Pint (US)' },
      { value: 'cup', label: 'Cup (US)' },
      { value: 'fl-oz', label: 'Fluid Ounce (US)' },
    ],
    factors: { l: 1, ml: 0.001, 'cubic-m': 1000, 'cubic-cm': 0.001, gal: 3.78541, qt: 0.946353, pt: 0.473176, cup: 0.236588, 'fl-oz': 0.0295735 },
  },
  speed: {
    name: 'Speed',
    units: [
      { value: 'm/s', label: 'Meter/second (m/s)' },
      { value: 'km/h', label: 'Kilometer/hour (km/h)' },
      { value: 'mph', label: 'Miles/hour (mph)' },
      { value: 'knot', label: 'Knot' },
      { value: 'ft/s', label: 'Foot/second (ft/s)' },
    ],
    factors: { 'm/s': 1, 'km/h': 0.277778, mph: 0.44704, knot: 0.514444, 'ft/s': 0.3048 },
  },
  time: {
    name: 'Time',
    units: [
      { value: 's', label: 'Second (s)' },
      { value: 'ms', label: 'Millisecond (ms)' },
      { value: 'μs', label: 'Microsecond (µs)' },
      { value: 'min', label: 'Minute (min)' },
      { value: 'hr', label: 'Hour (hr)' },
      { value: 'day', label: 'Day' },
      { value: 'week', label: 'Week' },
      { value: 'month', label: 'Month (30 days)' },
      { value: 'year', label: 'Year (365 days)' },
    ],
    factors: { s: 1, ms: 0.001, 'μs': 1e-6, min: 60, hr: 3600, day: 86400, week: 604800, month: 2.628e6, year: 3.154e7 },
  },
  pressure: {
    name: 'Pressure',
    units: [
        { value: 'Pa', label: 'Pascal (Pa)' },
        { value: 'kPa', label: 'Kilopascal (kPa)' },
        { value: 'bar', label: 'Bar' },
        { value: 'psi', label: 'PSI' },
        { value: 'atm', label: 'Atmosphere (atm)' },
        { value: 'torr', label: 'Torr' },
    ],
    factors: { Pa: 1, kPa: 1000, bar: 100000, psi: 6894.76, atm: 101325, torr: 133.322 },
  },
  energy: {
    name: 'Energy',
    units: [
        { value: 'J', label: 'Joule (J)' },
        { value: 'kJ', label: 'Kilojoule (kJ)' },
        { value: 'cal', label: 'Calorie (cal)' },
        { value: 'kcal', label: 'Kilocalorie (kcal)' },
        { value: 'kWh', label: 'Kilowatt-hour (kWh)' },
        { value: 'eV', label: 'Electronvolt (eV)' },
    ],
    factors: { J: 1, kJ: 1000, cal: 4.184, kcal: 4184, kWh: 3.6e6, eV: 1.6022e-19 },
  },
  power: {
    name: 'Power',
    units: [
        { value: 'W', label: 'Watt (W)' },
        { value: 'kW', label: 'Kilowatt (kW)' },
        { value: 'MW', label: 'Megawatt (MW)' },
        { value: 'hp', label: 'Horsepower (hp)' },
        { value: 'BTU/min', label: 'BTU/minute' },
    ],
    factors: { W: 1, kW: 1000, MW: 1e6, hp: 745.7, 'BTU/min': 17.5843 },
  },
  angle: {
    name: 'Angle',
    units: [
        { value: 'deg', label: 'Degree (°)' },
        { value: 'rad', label: 'Radian (rad)' },
        { value: 'grad', label: 'Gradian (grad)' },
        { value: 'turn', label: 'Turn' },
    ],
    factors: { deg: 1, rad: 57.2958, grad: 0.9, turn: 360 },
  },
  data: {
    name: 'Data Storage',
    units: [
      { value: 'B', label: 'Byte (B)' },
      { value: 'KB', label: 'Kilobyte (KB)' },
      { value: 'MB', label: 'Megabyte (MB)' },
      { value: 'GB', label: 'Gigabyte (GB)' },
      { value: 'TB', label: 'Terabyte (TB)' },
      { value: 'PB', label: 'Petabyte (PB)' },
    ],
    factors: { B: 1, KB: 1024, MB: 1024**2, GB: 1024**3, TB: 1024**4, PB: 1024**5 },
  },
};
