
'use client';

import { useState } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { aiWriter, type AiWriterInput } from '@/ai/flows/ai-writer';
import { Wand2, PlusCircle, UploadCloud, Send, Loader2, Save, Calendar as CalendarIcon, Clock } from 'lucide-react';
import Image from 'next/image';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';


const postSchema = z.object({
  title: z.string().min(5, { message: 'Title must be at least 5 characters long.' }),
  slug: z.string().min(5, { message: 'Slug must be at least 5 characters long.' }),
  content: z.string().min(50, { message: 'Content must be at least 50 characters long.' }),
  category: z.string().min(1, { message: 'Please select a category.' }),
  tags: z.string().optional(),
  scheduledDate: z.date().optional(),
});

type PostFormValues = z.infer<typeof postSchema>;

export default function AddNewPostPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [scheduledDate, setScheduledDate] = useState<Date | undefined>();
  const { toast } = useToast();

  const form = useForm<PostFormValues>({
    resolver: zodResolver(postSchema),
    defaultValues: {
      title: '',
      slug: '',
      content: '',
      category: '',
      tags: '',
    },
  });

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const title = e.target.value;
    form.setValue('title', title, { shouldValidate: true });
    const slug = title
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w-]+/g, '');
    form.setValue('slug', slug, { shouldValidate: true });
  };

  const handleGenerateContent = async () => {
    const title = form.getValues('title');
    if (!title) {
      toast({
        title: 'Title is required',
        description: 'Please enter a title to generate content.',
        variant: 'destructive',
      });
      return;
    }
    
    setIsGenerating(true);
    try {
      const result = await aiWriter({ topic: title });
      form.setValue('content', result.content);
      toast({
        title: 'Content Generated!',
        description: 'The post content has been successfully generated by AI.',
      });
    } catch (error: any) {
      console.error('AI generation failed:', error);
      toast({
        title: 'Generation Failed',
        description: error.message || 'Could not generate content. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePublish = async (values: PostFormValues) => {
    setIsPublishing(true);
    console.log('Publishing post:', { ...values, scheduledDate });
    await new Promise(resolve => setTimeout(resolve, 1500));
    toast({
      title: scheduledDate ? 'Post Scheduled!' : 'Post Published!',
      description: `Your post "${values.title}" has been successfully ${scheduledDate ? 'scheduled' : 'published'}.`,
    });
    setIsPublishing(false);
  };
  
  const handleSaveDraft = async () => {
    const values = form.getValues();
    setIsSavingDraft(true);
    console.log('Saving draft:', values);
    await new Promise(resolve => setTimeout(resolve, 1500));
    toast({
      title: 'Draft Saved',
      description: `Your post "${values.title}" has been saved as a draft.`,
    });
    setIsSavingDraft(false);
  };

  return (
    <div className="space-y-6">
       <div>
        <h1 className="text-3xl font-bold tracking-tight">Add New Post</h1>
        <p className="text-muted-foreground">
          Create a new blog post for your audience.
        </p>
      </div>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(handlePublish)} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Post Content</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="title"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Post Title</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., The Future of AI" {...field} onChange={handleTitleChange} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="slug"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Post Slug</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., the-future-of-ai" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <div className="relative">
                   <FormField
                    control={form.control}
                    name="content"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Post Body</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="Write your amazing blog post here, or generate it with AI..."
                            className="min-h-[400px] resize-y"
                            {...field}
                          />
                        </FormControl>
                         <FormMessage />
                      </FormItem>
                    )}
                  />
                  <Button 
                    type="button" 
                    onClick={handleGenerateContent} 
                    disabled={isGenerating}
                    variant="outline"
                    className="absolute bottom-4 right-4"
                    size="sm"
                  >
                    {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
                    Generate with AI
                  </Button>
                </div>

              </CardContent>
            </Card>
          </div>

          <div className="lg:col-span-1 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Publishing Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                 <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Status:</span>
                  <span className="font-semibold">Draft</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Visibility:</span>
                  <span className="font-semibold">Public</span>
                </div>
                 <div className="flex items-center justify-between text-sm">
                  <div className="flex items-center gap-2">
                    <CalendarIcon className="h-4 w-4 text-muted-foreground"/>
                    <span className="text-muted-foreground">Publish:</span>
                  </div>
                  <Popover>
                    <PopoverTrigger asChild>
                        <Button variant="link" className="p-0 h-auto font-semibold">
                          {scheduledDate ? format(scheduledDate, "PPP") : "Immediately"}
                        </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={scheduledDate}
                        onSelect={setScheduledDate}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <div className="flex flex-col sm:flex-row gap-2 pt-4">
                  <Button type="button" variant="outline" className="w-full" onClick={handleSaveDraft} disabled={isSavingDraft}>
                     {isSavingDraft ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                     Save Draft
                  </Button>
                  <Button type="submit" className="w-full" disabled={isPublishing}>
                    {isPublishing ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}
                    {scheduledDate ? 'Schedule' : 'Publish'}
                  </Button>
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Categories</CardTitle>
              </CardHeader>
              <CardContent>
                <FormField
                  control={form.control}
                  name="category"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Post Category</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select a category" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="technology">Technology</SelectItem>
                          <SelectItem value="ai">Artificial Intelligence</SelectItem>
                          <SelectItem value="productivity">Productivity</SelectItem>
                          <SelectItem value="news">News</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Tags</CardTitle>
              </CardHeader>
              <CardContent>
                 <FormField
                  control={form.control}
                  name="tags"
                  render={({ field }) => (
                    <FormItem>
                       <FormLabel>Post Tags</FormLabel>
                      <FormControl>
                        <Input placeholder="AI, SaaS, Tech..." {...field} />
                      </FormControl>
                      <p className="text-xs text-muted-foreground">Separate tags with commas.</p>
                       <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Featured Image</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="w-full border-2 border-dashed border-muted-foreground/30 rounded-lg p-6 text-center cursor-pointer hover:bg-muted/50">
                    <UploadCloud className="mx-auto h-10 w-10 text-muted-foreground mb-2" />
                    <p className="text-sm text-muted-foreground">Click to upload image</p>
                    <p className="text-xs text-muted-foreground">PNG, JPG, WEBP up to 5MB</p>
                </div>
              </CardContent>
            </Card>

          </div>
        </form>
      </Form>
    </div>
  );
}
