
'use client';

import dynamic from 'next/dynamic';
import * as React from 'react';
import { Loader2 } from 'lucide-react';

const LoadingComponent = () => (
  <div className="flex justify-center items-center min-h-[300px]">
    <Loader2 className="h-8 w-8 animate-spin text-primary" />
  </div>
);

export const slugToComponentMap: Record<string, React.FC<any>> = {
  'advance-text-cleaner': dynamic(() => import('@/components/tools/AdvanceTextCleaner'), { loading: LoadingComponent }),
  'admob-revenue-calculator': dynamic(() => import('@/components/tools/AdMobRevenueCalculator').then(mod => mod.AdMobRevenueCalculator), { loading: LoadingComponent }),
  'age-calculator': dynamic(() => import('@/components/tools/AgeCalculator'), { loading: LoadingComponent }),
  'amazon-shipping-label-cropper': dynamic(() => import('@/components/tools/AmazonShippingLabelCropper'), { loading: LoadingComponent }),
  'ascii-to-text-converter': dynamic(() => import('@/components/tools/AsciiToTextConverter'), { loading: LoadingComponent }),
  'average-calculator': dynamic(() => import('@/components/tools/AverageCalculator'), { loading: LoadingComponent }),
  'barcode-generator': dynamic(() => import('@/components/tools/BarcodeGenerator'), { loading: LoadingComponent }),
  'barcode-scanner': dynamic(() => import('@/components/tools/BarcodeScanner'), { loading: LoadingComponent }),
  'base64-encoder-and-decoder': dynamic(() => import('@/components/tools/Base64Converter'), { loading: LoadingComponent }),
  'binary-to-text': dynamic(() => import('@/components/tools/BinaryToText'), { loading: LoadingComponent }),
  'bmi-calculator': dynamic(() => import('@/components/tools/BmiCalculator'), { loading: LoadingComponent }),
  'case-converter': dynamic(() => import('@/components/tools/CaseConverter'), { loading: LoadingComponent }),
  'cgpa-to-gpa-converter': dynamic(() => import('@/components/tools/CgpaToGpaConverter'), { loading: LoadingComponent }),
  'cgpa-to-marks-calculator': dynamic(() => import('@/components/tools/CgpaToMarksCalculator'), { loading: LoadingComponent }),
  'color-picker': dynamic(() => import('@/components/tools/ColorPicker'), { loading: LoadingComponent }),
  'compress-pdf': dynamic(() => import('@/components/tools/CompressPdf'), { loading: LoadingComponent }),
  'credit-card-interest-calculator': dynamic(() => import('@/components/tools/CreditCardInterestCalculator'), { loading: LoadingComponent }),
  'crontab-generator': dynamic(() => import('@/components/tools/CrontabGenerator'), { loading: LoadingComponent }),
  'crypto-converter': dynamic(() => import('@/components/tools/CryptoConverter'), { loading: LoadingComponent }),
  'css-minifier': dynamic(() => import('@/components/tools/CssMinifier'), { loading: LoadingComponent }),
  'currency-converter': dynamic(() => import('@/components/tools/CurrencyConverter'), { loading: LoadingComponent }),
  'date-calculator': dynamic(() => import('@/components/tools/DateCalculator'), { loading: LoadingComponent }),
  'discount-calculator': dynamic(() => import('@/components/tools/DiscountCalculator'), { loading: LoadingComponent }),
  'driving-licence-photo-and-signature-resizer': dynamic(() => import('@/components/tools/DrivingLicenceResizer'), { loading: LoadingComponent }),
  'dropbox-direct-link-generator': dynamic(() => import('@/components/tools/DropboxDirectLinkGenerator'), { loading: LoadingComponent }),
  'excel-to-pdf': dynamic(() => import('@/components/tools/ExcelToPdf').then(mod => mod.ExcelToPdf), { loading: LoadingComponent }),
  'favicon-checker': dynamic(() => import('@/components/tools/FaviconChecker').then(mod => mod.FaviconChecker), { loading: LoadingComponent }),
  'find-and-replace': dynamic(() => import('@/components/tools/FindAndReplace').then(mod => mod.FindAndReplace), { loading: LoadingComponent }),
  'flipkart-shipping-label-cropper': dynamic(() => import('@/components/tools/FlipkartShippingLabelCropper').then(mod => mod.FlipkartShippingLabelCropper), { loading: LoadingComponent }),
  'flip-image': dynamic(() => import('@/components/tools/FlipImage').then(mod => mod.FlipImage), { loading: LoadingComponent }),
  'fuel-cost-calculator': dynamic(() => import('@/components/tools/FuelCostCalculator').then(mod => mod.FuelCostCalculator), { loading: LoadingComponent }),
  'gpa-calculator': dynamic(() => import('@/components/tools/GpaCalculator').then(mod => mod.GpaCalculator), { loading: LoadingComponent }),
  'gpa-to-cgpa-calculator': dynamic(() => import('@/components/tools/GpaToCgpaCalculator').then(mod => mod.GpaToCgpaCalculator), { loading: LoadingComponent }),
  'gpa-to-percentage-converter': dynamic(() => import('@/components/tools/GpaToPercentageConverter').then(mod => mod.GpaToPercentageConverter), { loading: LoadingComponent }),
  'gst-calculator': dynamic(() => import('@/components/tools/GSTCalculator').then(mod => mod.GSTCalculator), { loading: LoadingComponent }),
  'google-drive-direct-link-generator': dynamic(() => import('@/components/tools/GoogleDriveDirectLinkGenerator').then(mod => mod.GoogleDriveDirectLinkGenerator), { loading: LoadingComponent }),
  'html-minifier': dynamic(() => import('@/components/tools/HtmlMinifier').then(mod => mod.HtmlMinifier), { loading: LoadingComponent }),
  'html-to-markdown-converter': dynamic(() => import('@/components/tools/HtmlToMarkdownConverter').then(mod => mod.HtmlToMarkdownConverter), { loading: LoadingComponent }),
  'ico-converter': dynamic(() => import('@/components/tools/IcoConverter').then(mod => mod.IcoConverter), { loading: LoadingComponent }),
  'image-color-extractor': dynamic(() => import('@/components/tools/ImageColorExtractor').then(mod => mod.ImageColorExtractor), { loading: LoadingComponent }),
  'image-compressor': dynamic(() => import('@/components/tools/ImageCompressor').then(mod => mod.ImageCompressor), { loading: LoadingComponent }),
  'image-converter': dynamic(() => import('@/components/tools/ImageConverter').then(mod => mod.ImageConverter), { loading: LoadingComponent }),
  'image-cropper': dynamic(() => import('@/components/tools/ImageCropper').then(mod => mod.ImageCropper), { loading: LoadingComponent }),
  'image-grayscale-converter': dynamic(() => import('@/components/tools/ImageGrayscaleConverter').then(mod => mod.ImageGrayscaleConverter), { loading: LoadingComponent }),
  'image-resizer': dynamic(() => import('@/components/tools/ImageResizer').then(mod => mod.ImageResizer), { loading: LoadingComponent }),
  'image-shape-converter': dynamic(() => import('@/components/tools/ImageShapeConverter').then(mod => mod.ImageShapeConverter), { loading: LoadingComponent }),
  'image-to-base64': dynamic(() => import('@/components/tools/ImageToBase64').then(mod => mod.ImageToBase64), { loading: LoadingComponent }),
  'image-watermark-adder': dynamic(() => import('@/components/tools/ImageWatermarkAdder').then(mod => mod.ImageWatermarkAdder), { loading: LoadingComponent }),
  'image-metadata-viewer': dynamic(() => import('@/components/tools/ImageMetadataViewer').then(mod => mod.ImageMetadataViewer), { loading: LoadingComponent }),
  'interest-calculator': dynamic(() => import('@/components/tools/InterestCalculator').then(mod => mod.InterestCalculator), { loading: LoadingComponent }),
  'javascript-minifier': dynamic(() => import('@/components/tools/JavascriptMinifier').then(mod => mod.JavascriptMinifier), { loading: LoadingComponent }),
  'json-formatter': dynamic(() => import('@/components/tools/JsonFormatter').then(mod => mod.JsonFormatter), { loading: LoadingComponent }),
  'keyword-density-checker': dynamic(() => import('@/components/tools/KeywordDensityChecker').then(mod => mod.KeywordDensityChecker), { loading: LoadingComponent }),
  'loan-calculator': dynamic(() => import('@/components/tools/LoanCalculator').then(mod => mod.LoanCalculator), { loading: LoadingComponent }),
  'lock-pdf': dynamic(() => import('@/components/tools/LockPdf').then(mod => mod.LockPdf), { loading: LoadingComponent }),
  'lorem-ipsum-generator': dynamic(() => import('@/components/tools/LoremIpsumGenerator').then(mod => mod.LoremIpsumGenerator), { loading: LoadingComponent }),
  'marks-to-percentage-calculator': dynamic(() => import('@/components/tools/MarksToPercentageCalculator').then(mod => mod.MarksToPercentageCalculator), { loading: LoadingComponent }),
  'meesho-shipping-label-cropper': dynamic(() => import('@/components/tools/MeeshoShippingLabelCropper').then(mod => mod.MeeshoShippingLabelCropper), { loading: LoadingComponent }),
  'meta-tag-generator': dynamic(() => import('@/components/tools/MetaTagGenerator').then(mod => mod.MetaTagGenerator), { loading: LoadingComponent }),
  'morse-to-text-translator': dynamic(() => import('@/components/tools/MorseToTextTranslator').then(mod => mod.MorseToTextTranslator), { loading: LoadingComponent }),
  'myntra-shipping-label-cropper': dynamic(() => import('@/components/tools/MyntraShippingLabelCropper').then(mod => mod.MyntraShippingLabelCropper), { loading: LoadingComponent }),
  'negative-marking-calculator': dynamic(() => import('@/components/tools/NegativeMarkingCalculator').then(mod => mod.NegativeMarkingCalculator), { loading: LoadingComponent }),
  'nsdl-pan-card-photo-and-signature-resizer': dynamic(() => import('@/components/tools/NSDLPANCardPhotoAndSignatureResizer').then(mod => mod.NSDLPANCardPhotoAndSignatureResizer), { loading: LoadingComponent }),
  'onedrive-direct-link-generator': dynamic(() => import('@/components/tools/OneDriveDirectLinkGenerator').then(mod => mod.OneDriveDirectLinkGenerator), { loading: LoadingComponent }),
  'password-generator': dynamic(() => import('@/components/tools/PasswordGenerator').then(mod => mod.PasswordGenerator), { loading: LoadingComponent }),
  'password-strength-checker': dynamic(() => import('@/components/tools/PasswordStrengthChecker').then(mod => mod.PasswordStrengthChecker), { loading: LoadingComponent }),
  'pdf-merger': dynamic(() => import('@/components/tools/PdfMerger').then(mod => mod.PdfMerger), { loading: LoadingComponent }),
  'pdf-organizer': dynamic(() => import('@/components/tools/PdfOrganizer').then(mod => mod.PdfOrganizer), { loading: LoadingComponent }),
  'pdf-page-counter': dynamic(() => import('@/components/tools/PdfPageCounter').then(mod => mod.PdfPageCounter), { loading: LoadingComponent }),
  'pdf-page-numberer': dynamic(() => import('@/components/tools/PdfPageNumberer').then(mod => mod.PdfPageNumberer), { loading: LoadingComponent }),
  'pdf-page-remover': dynamic(() => import('@/components/tools/PdfPageRemover').then(mod => mod.PdfPageRemover), { loading: LoadingComponent }),
  'pdf-page-reorder': dynamic(() => import('@/components/tools/PdfPageReorder').then(mod => mod.PdfPageReorder), { loading: LoadingComponent }),
  'pdf-signer': dynamic(() => import('@/components/tools/PdfSigner').then(mod => mod.PdfSigner), { loading: LoadingComponent }),
  'pdf-splitter': dynamic(() => import('@/components/tools/PdfSplitter').then(mod => mod.PdfSplitter), { loading: LoadingComponent }),
  'pdf-to-jpg': dynamic(() => import('@/components/tools/PdfToJpg').then(mod => mod.PdfToJpg), { loading: LoadingComponent }),
  'pdf-to-word': dynamic(() => import('@/components/tools/PdfToWord').then(mod => mod.PdfToWord), { loading: LoadingComponent }),
  'percentage-calculator': dynamic(() => import('@/components/tools/PercentageCalculator').then(mod => mod.PercentageCalculator), { loading: LoadingComponent }),
  'percentage-to-cgpa-converter': dynamic(() => import('@/components/tools/PercentageToCgpaConverter').then(mod => mod.PercentageToCgpaConverter), { loading: LoadingComponent }),
  'ppt-to-pdf': dynamic(() => import('@/components/tools/PptToPdf').then(mod => mod.PptToPdf), { loading: LoadingComponent }),
  'qr-code-generator': dynamic(() => import('@/components/tools/QrCodeGenerator').then(mod => mod.QrCodeGenerator), { loading: LoadingComponent }),
  'qr-code-scanner': dynamic(() => import('@/components/tools/QrCodeScanner').then(mod => mod.QrCodeScanner), { loading: LoadingComponent }),
  'random-word-generator': dynamic(() => import('@/components/tools/RandomWordGenerator').then(mod => mod.RandomWordGenerator), { loading: LoadingComponent }),
  'readability-score-checker': dynamic(() => import('@/components/tools/ReadabilityScoreChecker').then(mod => mod.ReadabilityScoreChecker), { loading: LoadingComponent }),
  'remove-extra-spaces': dynamic(() => import('@/components/tools/RemoveExtraSpaces').then(mod => mod.RemoveExtraSpaces), { loading: LoadingComponent }),
  'redirect-checker': dynamic(() => import('@/components/tools/RedirectChecker').then(mod => mod.RedirectChecker), { loading: LoadingComponent }),
  'reverse-text': dynamic(() => import('@/components/tools/ReverseText').then(mod => mod.ReverseText), { loading: LoadingComponent }),
  'robots-txt-generator': dynamic(() => import('@/components/tools/RobotsTxtGenerator').then(mod => mod.RobotsTxtGenerator), { loading: LoadingComponent }),
  'rotate-image': dynamic(() => import('@/components/tools/RotateImage').then(mod => mod.RotateImage), { loading: LoadingComponent }),
  'rotate-pdf': dynamic(() => import('@/components/tools/RotatePdf').then(mod => mod.RotatePdf), { loading: LoadingComponent }),
  'schema-generator': dynamic(() => import('@/components/tools/SchemaGenerator').then(mod => mod.SchemaGenerator), { loading: LoadingComponent }),
  'serp-checker': dynamic(() => import('@/components/tools/SerpChecker').then(mod => mod.SerpChecker), { loading: LoadingComponent }),
  'sha256-hash-generator': dynamic(() => import('@/components/tools/Sha256HashGenerator').then(mod => mod.Sha256HashGenerator), { loading: LoadingComponent }),
  'sku-encryptor': dynamic(() => import('@/components/tools/SkuEncryptor').then(mod => mod.SkuEncryptor), { loading: LoadingComponent }),
  'srm-to-cgpa-calculator': dynamic(() => import('@/components/tools/SrmToCgpaCalculator').then(mod => mod.SrmToCgpaCalculator), { loading: LoadingComponent }),
  'sql-formatter': dynamic(() => import('@/components/tools/SqlFormatter').then(mod => mod.SqlFormatter), { loading: LoadingComponent }),
  'text-repeater': dynamic(() => import('@/components/tools/TextRepeater').then(mod => mod.TextRepeater), { loading: LoadingComponent }),
  'text-to-binary': dynamic(() => import('@/components/tools/TextToBinary').then(mod => mod.TextToBinary), { loading: LoadingComponent }),
  'text-to-morse-code': dynamic(() => import('@/components/tools/TextToMorseCode').then(mod => mod.TextToMorseCode), { loading: LoadingComponent }),
  'file-encryption-and-decryption': dynamic(() => import('@/components/tools/FileEncryptionDecryption').then(mod => mod.FileEncryptionDecryption), { loading: LoadingComponent }),
  'image-to-text': dynamic(() => import('@/components/tools/ImageToText').then(mod => mod.ImageToText), { loading: LoadingComponent }),
  'time-zone-converter': dynamic(() => import('@/components/tools/TimeZoneConverter').then(mod => mod.TimeZoneConverter), { loading: LoadingComponent }),
  'title-tag-checker': dynamic(() => import('@/components/tools/TitleTagChecker').then(mod => mod.TitleTagChecker), { loading: LoadingComponent }),
  'unix-timestamp-converter': dynamic(() => import('@/components/tools/UnixTimestampConverter').then(mod => mod.UnixTimestampConverter), { loading: LoadingComponent }),
  'universal-hash-generator': dynamic(() => import('@/components/tools/UniversalHashGenerator').then(mod => mod.UniversalHashGenerator), { loading: LoadingComponent }),
  'unlock-pdf': dynamic(() => import('@/components/tools/UnlockPdf').then(mod => mod.UnlockPdf), { loading: LoadingComponent }),
  'url-shortener': dynamic(() => import('@/components/tools/UrlShortener').then(mod => mod.UrlShortener), { loading: LoadingComponent }),
  'uuid-generator': dynamic(() => import('@/components/tools/UuidGenerator').then(mod => mod.UuidGenerator), { loading: LoadingComponent }),
  'uti-pan-card-photo-and-signature-resizer': dynamic(() => import('@/components/tools/UTIPANCardPhotoAndSignatureResizer').then(mod => mod.UTIPANCardPhotoAndSignatureResizer), { loading: LoadingComponent }),
  'website-screenshot': dynamic(() => import('@/components/tools/WebsiteScreenshot').then(mod => mod.WebsiteScreenshot), { loading: LoadingComponent }),
  'website-word-counter': dynamic(() => import('@/components/tools/WebsiteWordCounter').then(mod => mod.WebsiteWordCounter), { loading: LoadingComponent }),
  'what-is-my-browser': dynamic(() => import('@/components/tools/WhatIsMyBrowser').then(mod => mod.WhatIsMyBrowser), { loading: LoadingComponent }),
  'word-counter': dynamic(() => import('@/components/tools/WordCounter').then(mod => mod.WordCounter), { loading: LoadingComponent }),
  'word-to-pdf': dynamic(() => import('@/components/tools/WordToPdf').then(mod => mod.WordToPdf), { loading: LoadingComponent }),
  'xml-sitemap-generator': dynamic(() => import('@/components/tools/XmlSitemapGenerator').then(mod => mod.XmlSitemapGenerator), { loading: LoadingComponent }),
  'youtube-banner-downloader': dynamic(() => import('@/components/tools/YouTubeChannelBannerDownloader').then(mod => mod.YouTubeChannelBannerDownloader), { loading: LoadingComponent }),
  'youtube-logo-downloader': dynamic(() => import('@/components/tools/YouTubeChannelLogoDownloader').then(mod => mod.YouTubeChannelLogoDownloader), { loading: LoadingComponent }),
  'youtube-region-restriction-checker': dynamic(() => import('@/components/tools/YouTubeRegionRestrictionChecker').then(mod => mod.YouTubeRegionRestrictionChecker), { loading: LoadingComponent }),
  'youtube-video-description-extractor': dynamic(() => import('@/components/tools/YouTubeVideoDescriptionExtractor').then(mod => mod.YouTubeVideoDescriptionExtractor), { loading: LoadingComponent }),
  'youtube-video-thumbnail-downloader': dynamic(() => import('@/components/tools/YouTubeVideoThumbnailDownloader').then(mod => mod.YouTubeVideoThumbnailDownloader), { loading: LoadingComponent }),
  'youtube-video-title-extractor': dynamic(() => import('@/components/tools/YouTubeVideoTitleExtractor').then(mod => mod.YouTubeVideoTitleExtractor), { loading: LoadingComponent }),
  'profit-loss-calculator': dynamic(() => import('@/components/tools/ProfitLossCalculator').then(mod => mod.ProfitLossCalculator), { loading: LoadingComponent }),
  'sip-calculator': dynamic(() => import('@/components/tools/SIPCalculator').then(mod => mod.SIPCalculator), { loading: LoadingComponent }),
  'fd-calculator': dynamic(() => import('@/components/tools/FDCalculator').then(mod => mod.FDCalculator), { loading: LoadingComponent }),
  'mutual-fund-calculator': dynamic(() => import('@/components/tools/MutualFundCalculator').then(mod => mod.MutualFundCalculator), { loading: LoadingComponent }),
  'sales-tax-calculator': dynamic(() => import('@/components/tools/SalesTaxCalculator').then(mod => mod.SalesTaxCalculator), { loading: LoadingComponent }),
  'tds-calculator': dynamic(() => import('@/components/tools/TDSCalculator').then(mod => mod.TDSCalculator), { loading: LoadingComponent }),
  'image-aspect-ratio-calculator': dynamic(() => import('@/components/tools/ImageAspectRatioCalculator').then(mod => mod.ImageAspectRatioCalculator), { loading: LoadingComponent }),
  'spelling-checker': dynamic(() => import('@/components/tools/SpellingChecker').then(mod => mod.SpellingChecker), { loading: LoadingComponent }),
  'whats-chat-url-generator': dynamic(() => import('@/components/tools/WhatsChatUrlGenerator').then(mod => mod.WhatsChatUrlGenerator), { loading: LoadingComponent }),
  'whats-app-group-url-generator': dynamic(() => import('@/components/tools/WhatsAppGroupUrlGenerator').then(mod => mod.WhatsAppGroupUrlGenerator), { loading: LoadingComponent }),
  'internet-speed-tester': dynamic(() => import('@/components/tools/InternetSpeedTester').then(mod => mod.InternetSpeedTester), { loading: LoadingComponent }),
  'device-information-detector': dynamic(() => import('@/components/tools/DeviceInformationDetector').then(mod => mod.DeviceInformationDetector), { loading: LoadingComponent }),
  'numbers-to-word': dynamic(() => import('@/components/tools/NumbersToWord').then(mod => mod.NumbersToWord), { loading: LoadingComponent }),
  'emoji-remover': dynamic(() => import('@/components/tools/EmojiRemover').then(mod => mod.EmojiRemover), { loading: LoadingComponent }),
  'roman-to-number-converter': dynamic(() => import('@/components/tools/RomanToNumberConverter').then(mod => mod.RomanToNumberConverter), { loading: LoadingComponent }),
  'number-to-roman-converter': dynamic(() => import('@/components/tools/NumberToRomanConverter').then(mod => mod.NumberToRomanConverter), { loading: LoadingComponent }),
  'rd-calculator': dynamic(() => import('@/components/tools/RdCalculator').then(mod => mod.RdCalculator), { loading: LoadingComponent }),
  'nps-calculator': dynamic(() => import('@/components/tools/NpsCalculator').then(mod => mod.NpsCalculator), { loading: LoadingComponent }),
  'adsense-revenue-calculator': dynamic(() => import('@/components/tools/AdSenseRevenueCalculator').then(mod => mod.AdSenseRevenueCalculator), { loading: LoadingComponent }),
  'unit-converter': dynamic(() => import('@/components/tools/UnitConverter').then(mod => mod.UnitConverter), { loading: LoadingComponent }),
  'image-to-pdf': dynamic(() => import('@/components/tools/ImageToPdf').then(mod => mod.ImageToPdf), { loading: LoadingComponent }),
  'epf-calculator': dynamic(() => import('@/components/tools/EPFCalculator').then(mod => mod.EPFCalculator), { loading: LoadingComponent }),
  'gratuity-calculator': dynamic(() => import('@/components/tools/GratuityCalculator').then(mod => mod.GratuityCalculator), { loading: LoadingComponent }),
  'inflation-calculator': dynamic(() => import('@/components/tools/InflationCalculator').then(mod => mod.InflationCalculator), { loading: LoadingComponent }),
  'loan-affordability-calculator': dynamic(() => import('@/components/tools/LoanAffordabilityCalculator').then(mod => mod.LoanAffordabilityCalculator), { loading: LoadingComponent }),
  'nsc-calculator': dynamic(() => import('@/components/tools/NscCalculator').then(mod => mod.NscCalculator), { loading: LoadingComponent }),
  'ppf-calculator': dynamic(() => import('@/components/tools/PpfCalculator').then(mod => mod.PpfCalculator), { loading: LoadingComponent }),
  'swp-calculator': dynamic(() => import('@/components/tools/SwpCalculator').then(mod => mod.SwpCalculator), { loading: LoadingComponent }),
  'retirement-savings-calculator': dynamic(() => import('@/components/tools/RetirementSavingsCalculator').then(mod => mod.RetirementSavingsCalculator), { loading: LoadingComponent }),
  'mortgage-calculator': dynamic(() => import('@/components/tools/MortgageCalculator').then(mod => mod.MortgageCalculator), { loading: LoadingComponent }),
  'hra-calculator': dynamic(() => import('@/components/tools/HraCalculator').then(mod => mod.HraCalculator), { loading: LoadingComponent }),
  'text-to-handwriting-converter': dynamic(() => import('@/components/tools/TextToHandwritingConverter').then(mod => mod.TextToHandwritingConverter), { loading: LoadingComponent }),
  'text-to-ascii-converter': dynamic(() => import('@/components/tools/TextToAsciiConverter').then(mod => mod.TextToAsciiConverter), { loading: LoadingComponent }),
  'random-name-generator': dynamic(() => import('@/components/tools/RandomNameGenerator').then(mod => mod.RandomNameGenerator), { loading: LoadingComponent }),
  'ifsc-code-to-bank-details': dynamic(() => import('@/components/tools/IfscCodeToBankDetails').then(mod => mod.IfscCodeToBankDetails), { loading: LoadingComponent }),
  'text-to-speech': dynamic(() => import('@/components/tools/TextToSpeech').then(mod => mod.TextToSpeechTool), { loading: LoadingComponent }),
};
