
'use client';

import { useState, useRef } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { aiWriter } from '@/ai/flows/ai-writer';
import { upsertPost } from '@/ai/flows/blog-management';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { Wand2, UploadCloud, Send, Loader2, Save, ArrowLeft, Link as LinkIcon, Target } from 'lucide-react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { RichTextEditor } from '@/components/common/RichTextEditor';

const postSchema = z.object({
  title: z.string().min(5, { message: 'Title must be at least 5 characters long.' }),
  slug: z.string().min(5, { message: 'Slug must be at least 5 characters long.' }),
  content: z.string().min(50, { message: 'Content must be at least 50 characters long.' }),
  category: z.string().min(1, { message: 'Please select a category.' }),
  tags: z.string().optional(),
  status: z.enum(['Published', 'Draft', 'Scheduled', 'Trash']),
  metaDescription: z.string().optional(),
  targetKeyword: z.string().optional(),
  inboundLinks: z.string().optional(),
  outboundLinks: z.string().optional(),
});

type PostFormValues = z.infer<typeof postSchema>;

export default function AddNewPostPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();
  const router = useRouter();

  const form = useForm<PostFormValues>({
    resolver: zodResolver(postSchema),
    defaultValues: {
      title: '',
      slug: '',
      content: '',
      category: '',
      tags: '',
      status: 'Draft',
      metaDescription: '',
      targetKeyword: '',
      inboundLinks: '',
      outboundLinks: '',
    },
  });

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const title = e.target.value;
    form.setValue('title', title, { shouldValidate: true });
    const slug = title
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w-]+/g, '');
    form.setValue('slug', slug, { shouldValidate: true });
  };
  
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) { // 5MB limit
        toast({ title: "File too large", description: "Image must be smaller than 5MB.", variant: "destructive" });
        return;
      }
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handleGenerateContent = async () => {
    const title = form.getValues('title');
    if (!title) {
      toast({
        title: 'Title is required',
        description: 'Please enter a title to generate content.',
        variant: 'destructive',
      });
      return;
    }
    
    setIsGenerating(true);
    try {
      const result = await aiWriter({ topic: title });
      form.setValue('content', result.content);
      toast({
        title: 'Content Generated!',
        description: 'The post content has been successfully generated by AI.',
      });
    } catch (error: any) {
      console.error('AI generation failed:', error);
      toast({
        title: 'Generation Failed',
        description: error.message || 'Could not generate content. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const processAndSavePost = async (values: PostFormValues) => {
    setIsSaving(true);
    try {
      let imageUrl: string | undefined = undefined;
      if (imageFile) {
        const storage = getStorage();
        const storageRef = ref(storage, `blog-images/${Date.now()}-${imageFile.name}`);
        const snapshot = await uploadBytes(storageRef, imageFile);
        imageUrl = await getDownloadURL(snapshot.ref);
      }
      
      const postData = {
          ...values,
          imageUrl,
          imageHint: values.title.split(' ').slice(0, 2).join(' '),
          tags: values.tags?.split(',').map(tag => tag.trim()).filter(Boolean) || [],
      };

      const result = await upsertPost(postData);

      if (result.success) {
         toast({
          title: `Post ${values.status}!`,
          description: `Your post "${values.title}" has been successfully saved.`,
        });
        router.push('/admin/blog/all-posts');
      } else {
        throw new Error(result.message);
      }

    } catch (error: any) {
      toast({ title: 'Error', description: error.message || 'Could not save the post.', variant: 'destructive'});
    } finally {
      setIsSaving(false);
    }
  }

  const handlePostSubmit = (status: PostFormValues['status']) => {
    form.setValue('status', status);
    form.handleSubmit(processAndSavePost)();
  };

  return (
    <div className="space-y-6">
      <Form {...form}>
        <form>
          <div className="flex items-center justify-between mb-6">
             <div>
                <Link href="/admin/blog/all-posts" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-2">
                  <ArrowLeft className="h-4 w-4" />
                  Back To All Posts
                </Link>
                <h1 className="text-3xl font-bold tracking-tight">Add New Post</h1>
              </div>
              <div className="flex gap-2">
                <Button type="button" variant="outline" onClick={() => handlePostSubmit('Draft')} disabled={isSaving}>
                   <Save className="mr-2 h-4 w-4" />
                   Save Draft
                </Button>
                <Button type="button" onClick={() => handlePostSubmit('Published')} disabled={isSaving}>
                  {isSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Send className="mr-2 h-4 w-4" />}
                  Publish
                </Button>
              </div>
          </div>
        
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle>Post Details</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                            <FormField
                                control={form.control}
                                name="title"
                                render={({ field }) => (
                                    <FormItem className="lg:col-span-2">
                                    <FormLabel>Post Title</FormLabel>
                                    <FormControl>
                                        <Input placeholder="e.g., The Future of AI" {...field} onChange={handleTitleChange} />
                                    </FormControl>
                                    <FormMessage />
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="slug"
                                render={({ field }) => (
                                    <FormItem className="lg:col-span-2">
                                    <FormLabel>Post Slug</FormLabel>
                                    <FormControl>
                                        <Input placeholder="e.g., the-future-of-ai" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                    </FormItem>
                                )}
                            />
                             <FormField
                                control={form.control}
                                name="category"
                                render={({ field }) => (
                                <FormItem className="lg:col-span-2">
                                    <FormLabel>Category</FormLabel>
                                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                                    <FormControl>
                                        <SelectTrigger>
                                        <SelectValue placeholder="Select a category" />
                                        </SelectTrigger>
                                    </FormControl>
                                    <SelectContent>
                                        <SelectItem value="technology">Technology</SelectItem>
                                        <SelectItem value="ai">Artificial Intelligence</SelectItem>
                                        <SelectItem value="productivity">Productivity</SelectItem>
                                        <SelectItem value="news">News</SelectItem>
                                    </SelectContent>
                                    </Select>
                                    <FormMessage />
                                </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="tags"
                                render={({ field }) => (
                                <FormItem className="lg:col-span-2">
                                    <FormLabel>Tags</FormLabel>
                                    <FormControl>
                                    <Input placeholder="AI, SaaS, Tech..." {...field} />
                                    </FormControl>
                                    <p className="text-xs text-muted-foreground">Separate tags with commas.</p>
                                    <FormMessage />
                                </FormItem>
                                )}
                            />
                        </div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader>
                        <CardTitle>Post Content</CardTitle>
                    </CardHeader>
                    <CardContent>
                       <div className="relative">
                            <FormField
                                control={form.control}
                                name="content"
                                render={({ field }) => (
                                    <FormItem>
                                    <FormLabel className="sr-only">Post Body</FormLabel>
                                    <FormControl>
                                        <RichTextEditor
                                            value={field.value}
                                            onChange={field.onChange}
                                            placeholder="Write your amazing blog post here, or generate it with AI..."
                                            className="min-h-[400px]"
                                        />
                                    </FormControl>
                                    <FormMessage />
                                    </FormItem>
                                )}
                            />
                            <Button 
                            type="button" 
                            onClick={handleGenerateContent} 
                            disabled={isGenerating}
                            variant="outline"
                            className="absolute bottom-4 right-4 z-10"
                            size="sm"
                            >
                            {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
                            Generate with AI
                            </Button>
                        </div>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle>SEO Settings</CardTitle>
                        <CardDescription>Optimize your post for search engines.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <FormField
                            control={form.control}
                            name="metaDescription"
                            render={({ field }) => (
                                <FormItem>
                                <FormLabel>Meta Description</FormLabel>
                                <FormControl><Textarea {...field} placeholder="A short, compelling description for search results (max 160 characters)." maxLength={160} /></FormControl>
                                <FormMessage />
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="targetKeyword"
                            render={({ field }) => (
                                <FormItem>
                                <FormLabel className="flex items-center gap-2"><Target className="h-4 w-4"/> Target Keyword</FormLabel>
                                <FormControl><Input {...field} placeholder="e.g., 'best ai tools'" /></FormControl>
                                <FormMessage />
                                </FormItem>
                            )}
                        />
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <FormField
                                control={form.control}
                                name="inboundLinks"
                                render={({ field }) => (
                                    <FormItem>
                                    <FormLabel className="flex items-center gap-2"><LinkIcon className="h-4 w-4"/> Inbound Links</FormLabel>
                                    <FormControl><Textarea {...field} placeholder="One URL per line" /></FormControl>
                                    <FormMessage />
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="outboundLinks"
                                render={({ field }) => (
                                    <FormItem>
                                    <FormLabel className="flex items-center gap-2"><LinkIcon className="h-4 w-4"/> Outbound Links</FormLabel>
                                    <FormControl><Textarea {...field} placeholder="One URL per line" /></FormControl>
                                    <FormMessage />
                                    </FormItem>
                                )}
                            />
                        </div>
                    </CardContent>
                </Card>
            </div>
            <div className="lg:col-span-1 space-y-6">
                 <Card>
                    <CardHeader>
                    <CardTitle>Featured Image</CardTitle>
                    </CardHeader>
                    <CardContent>
                    <div 
                        className="w-full aspect-video border-2 border-dashed border-muted-foreground/30 rounded-lg text-center cursor-pointer hover:bg-muted/50 flex items-center justify-center relative"
                        onClick={() => fileInputRef.current?.click()}
                    >
                        <input type="file" ref={fileInputRef} onChange={handleFileChange} className="hidden" accept="image/png, image/jpeg, image/webp" />
                        {imagePreview ? (
                            <Image src={imagePreview} alt="Featured image preview" fill className="object-cover rounded-md" />
                        ) : (
                            <div className="flex flex-col items-center">
                                <UploadCloud className="mx-auto h-10 w-10 text-muted-foreground mb-2" />
                                <p className="text-sm text-muted-foreground">Click to upload image</p>
                                <p className="text-xs text-muted-foreground">PNG, JPG, WEBP up to 5MB</p>
                            </div>
                        )}
                    </div>
                    </CardContent>
                </Card>
            </div>
          </div>
        </form>
      </Form>
    </div>
  );
}
