

'use client';

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { composeEmail, type AiEmailComposerInput } from '@/ai/flows/ai-email-composer';
import { Wand2, Send, Mail, Eye, Users } from 'lucide-react';
import { z } from 'zod';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDesc, DialogFooter, DialogTrigger } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import Link from 'next/link';


// Re-define the base schema on the client and then extend it.
const formSchema = z.object({
  subject: z.string().min(1, 'Subject is required.'),
  keyPoints: z.string().min(1, 'Email content or key points are required.'),
  tone: z.enum(['Formal', 'Casual', 'Friendly', 'Professional', 'Humorous']),
  recipient: z.string().optional(),
});


type ComposeFormValues = z.infer<typeof formSchema>;

export default function ComposeEmailPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [generatedBody, setGeneratedBody] = useState('');
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);
  const [sendToAll, setSendToAll] = useState(false);
  const { toast } = useToast();

  const form = useForm<ComposeFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      recipient: '',
      subject: '',
      keyPoints: '',
      tone: 'Professional',
    },
  });
  
  // Watch the sendToAll state to update validation rules
  useEffect(() => {
    if (sendToAll) {
      form.clearErrors('recipient');
    } else {
        const recipientValue = form.getValues('recipient');
        if (!recipientValue) {
             form.setError('recipient', { type: 'manual', message: 'At least one recipient email is required.' });
        }
    }
  }, [sendToAll, form]);


  const handleGenerate = async () => {
    const { subject, keyPoints, tone } = form.getValues();
    if (!subject || !keyPoints) {
      toast({
        title: 'Missing Information',
        description: 'Please provide a subject and some key points to generate the email.',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      const result = await composeEmail({ subject, keyPoints, tone: tone as AiEmailComposerInput['tone'] });
      setGeneratedBody(result.emailBody);
      form.setValue('keyPoints', result.emailBody);
      toast({
        title: 'Content Generated!',
        description: 'The email body has been generated by AI.',
      });
    } catch (error: any) {
      console.error('AI generation failed:', error);
      toast({
        title: 'Generation Failed',
        description: error.message || 'Could not generate email content. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };
  
  const handleSend = async (values: ComposeFormValues) => {
    if (!sendToAll && !values.recipient) {
      form.setError('recipient', { type: 'manual', message: 'Please provide at least one recipient email.' });
      return;
    }
    
    setIsSending(true);
    // This is a placeholder for the actual email sending logic
    const recipientDescription = sendToAll ? 'all users' : values.recipient;
    console.log('Sending email to:', recipientDescription, 'with content:', values);
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate API call
    toast({
      title: 'Email Sent (Simulated)',
      description: `Your email has been queued for sending to ${recipientDescription}.`,
    });
    setIsSending(false);
    // form.reset();
    // setGeneratedBody('');
  };


  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
            <h1 className="text-3xl font-bold tracking-tight">AI Email Composer</h1>
            <p className="text-muted-foreground">
              Create and send emails with the help of AI.
            </p>
        </div>
        <Button variant="outline" asChild>
           <Link href="/admin/email/all-emails">
            <Mail className="mr-2 h-4 w-4" />
            View Sent Emails
           </Link>
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Compose New Email</CardTitle>
          <CardDescription>
            Fill in the details below. Use the AI generator for the main content.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(handleSend)} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 <FormField
                  control={form.control}
                  name="recipient"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Recipient(s)</FormLabel>
                      <FormControl>
                        <Input 
                            placeholder="user@example.com, another@example.com" 
                            {...field} 
                            disabled={sendToAll}
                            value={field.value || ''}
                         />
                      </FormControl>
                      <FormDescription>Separate multiple emails with commas.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                 <FormField
                  control={form.control}
                  name="subject"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Subject</FormLabel>
                      <FormControl>
                        <Input placeholder="Regarding your recent inquiry" {...field} />
                      </FormControl>
                       <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                 <FormField
                    control={form.control}
                    name="tone"
                    render={({ field }) => (
                        <FormItem>
                        <FormLabel>Tone of Voice</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                            <FormControl>
                            <SelectTrigger>
                                <SelectValue placeholder="Select a tone" />
                            </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                            <SelectItem value="Professional">Professional</SelectItem>
                            <SelectItem value="Casual">Casual</SelectItem>
                            <SelectItem value="Friendly">Friendly</SelectItem>
                            <SelectItem value="Formal">Formal</SelectItem>
                            <SelectItem value="Humorous">Humorous</SelectItem>
                            </SelectContent>
                        </Select>
                        <FormMessage />
                        </FormItem>
                    )}
                 />
                 <div className="flex items-center justify-between rounded-lg border p-4">
                      <div className="space-y-0.5">
                        <Label htmlFor="send-to-all" className="text-base font-medium flex items-center">
                            <Users className="mr-2 h-5 w-5"/>
                             Send to All Users
                        </Label>
                        <p className="text-sm text-muted-foreground">
                            Overrides the recipient list and sends to all subscribers.
                        </p>
                      </div>
                      <Switch 
                        id="send-to-all" 
                        checked={sendToAll}
                        onCheckedChange={setSendToAll}
                       />
                 </div>
              </div>

              <div className="space-y-2">
                 <FormField
                  control={form.control}
                  name="keyPoints"
                  render={({ field }) => (
                     <FormItem>
                       <FormLabel>Email Content / Key Points</FormLabel>
                       <FormControl>
                        <Textarea
                          placeholder="Enter the main points for the AI, or write the full email here."
                          className="min-h-[150px] resize-y"
                          {...field}
                         />
                       </FormControl>
                       <FormMessage />
                     </FormItem>
                  )}
                 />
              </div>
              
               <div className="flex flex-col sm:flex-row gap-4">
                  <Button type="button" onClick={handleGenerate} disabled={isGenerating} className="w-full sm:w-auto">
                    <Wand2 className="mr-2 h-4 w-4" />
                    {isGenerating ? 'Generating...' : 'Generate with AI'}
                  </Button>
                  <Dialog open={isPreviewOpen} onOpenChange={setIsPreviewOpen}>
                    <DialogTrigger asChild>
                       <Button type="button" variant="outline" className="w-full sm:w-auto">
                        <Eye className="mr-2 h-4 w-4" />
                        Preview
                      </Button>
                    </DialogTrigger>
                    <DialogContent className="sm:max-w-[625px]">
                       <DialogHeader>
                        <DialogTitle>Email Preview</DialogTitle>
                         <DialogDesc>
                          This is a preview of the email that will be sent to {form.getValues().recipient || '...'}
                        </DialogDesc>
                      </DialogHeader>
                      <div className="space-y-4 py-4">
                         <h3 className="font-semibold">Subject: {form.getValues().subject || '...'}</h3>
                        <div className="p-4 border rounded-lg bg-muted min-h-[200px] whitespace-pre-wrap">
                          {form.getValues().keyPoints || 'Email body will appear here...'}
                        </div>
                      </div>
                    </DialogContent>
                  </Dialog>
                   <Button type="submit" disabled={isSending} className="w-full sm:w-auto">
                    <Send className="mr-2 h-4 w-4" />
                    {isSending ? 'Sending...' : 'Send Email'}
                  </Button>
               </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}
