
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { composeEmail, AiEmailComposerInputSchema, type AiEmailComposerInput } from '@/ai/flows/ai-email-composer';
import { Wand2, Send, Mail } from 'lucide-react';
import { z } from 'zod';


const formSchema = AiEmailComposerInputSchema.extend({
  recipient: z.string().email({ message: 'Please enter a valid email address.' }),
});

type ComposeFormValues = z.infer<typeof formSchema>;

export default function ComposeEmailPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [generatedBody, setGeneratedBody] = useState('');
  const { toast } = useToast();

  const form = useForm<ComposeFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      recipient: '',
      subject: '',
      keyPoints: '',
      tone: 'Professional',
    },
  });

  const handleGenerate = async () => {
    const { subject, keyPoints, tone } = form.getValues();
    if (!subject || !keyPoints) {
      toast({
        title: 'Missing Information',
        description: 'Please provide a subject and some key points to generate the email.',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      const result = await composeEmail({ subject, keyPoints, tone });
      setGeneratedBody(result.emailBody);
      form.setValue('keyPoints', result.emailBody);
      toast({
        title: 'Content Generated!',
        description: 'The email body has been generated by AI.',
      });
    } catch (error: any) {
      console.error('AI generation failed:', error);
      toast({
        title: 'Generation Failed',
        description: error.message || 'Could not generate email content. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };
  
  const handleSend = async (values: ComposeFormValues) => {
    setIsSending(true);
    // This is a placeholder for the actual email sending logic
    console.log('Sending email:', values);
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate API call
    toast({
      title: 'Email Sent (Simulated)',
      description: `Your email to ${values.recipient} has been sent.`,
    });
    setIsSending(false);
    // form.reset();
    // setGeneratedBody('');
  };


  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
            <h1 className="text-3xl font-bold tracking-tight">AI Email Composer</h1>
            <p className="text-muted-foreground">
              Create and send emails with the help of AI.
            </p>
        </div>
        <Button variant="outline" disabled>
            <Mail className="mr-2 h-4 w-4" />
            View Sent Emails
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Compose New Email</CardTitle>
          <CardDescription>
            Fill in the details below. Use the AI generator for the main content.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(handleSend)} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <FormField
                    control={form.control}
                    name="recipient"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Recipient Email</FormLabel>
                        <FormControl>
                          <Input placeholder="user@example.com" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
                <div className="space-y-2">
                  <FormField
                    control={form.control}
                    name="subject"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Subject</FormLabel>
                        <FormControl>
                          <Input placeholder="Regarding your recent inquiry" {...field} />
                        </FormControl>
                         <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </div>
              
              <div className="space-y-2">
                <FormField
                  control={form.control}
                  name="tone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Tone of Voice</FormLabel>
                       <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select a tone" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="Professional">Professional</SelectItem>
                          <SelectItem value="Casual">Casual</SelectItem>
                          <SelectItem value="Friendly">Friendly</SelectItem>
                          <SelectItem value="Formal">Formal</SelectItem>
                          <SelectItem value="Humorous">Humorous</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="space-y-2">
                 <FormField
                  control={form.control}
                  name="keyPoints"
                  render={({ field }) => (
                     <FormItem>
                       <FormLabel>Email Content / Key Points</FormLabel>
                       <FormControl>
                        <Textarea
                          placeholder="Enter the main points for the AI, or write the full email here."
                          className="min-h-[150px] resize-y"
                          {...field}
                         />
                       </FormControl>
                       <FormMessage />
                     </FormItem>
                  )}
                 />
              </div>
              
               <div className="flex flex-col sm:flex-row gap-4">
                  <Button type="button" onClick={handleGenerate} disabled={isGenerating} className="w-full sm:w-auto">
                    <Wand2 className="mr-2 h-4 w-4" />
                    {isGenerating ? 'Generating...' : 'Generate with AI'}
                  </Button>
                   <Button type="submit" disabled={isSending} className="w-full sm:w-auto">
                    <Send className="mr-2 h-4 w-4" />
                    {isSending ? 'Sending...' : 'Send Email'}
                  </Button>
               </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}
